# =============================================================================
# Docker Compose Local Development Override
# Uses locally built images with source code mounting for development
# =============================================================================

services:
  # Development database
  database:
    image: postgres:16
    environment:
      # Map standard .env variables to what Postgres container expects
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    
  # Backend built locally
  backend:
    build:
      context: ${PROJECT_ROOT_DIR:-/home/user/milou}/dashboard
      dockerfile: backend/Dockerfile.backend
    environment:
      - NODE_ENV=production
      - DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT:-5432}/${DB_NAME}?sslmode=disable
      - PORT=${PORT:-9999}
      - DB_HOST=database
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-milou_database}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      - SESSION_SECRET=${SESSION_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SSO_CONFIG_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${SESSION_SECRET}
      - FRONTEND_URL=https://${DOMAIN:-localhost}
      - BACKEND_URL=https://${DOMAIN:-localhost}:${PORT:-9999}/
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  # Frontend built locally
  frontend:
    build:
      context: ${PROJECT_ROOT_DIR:-/home/user/milou}/dashboard
      dockerfile: frontend/Dockerfile.frontend
    environment:
      - NODE_ENV=production
      - VITE_DOMAIN=${DOMAIN}

  # Engine built locally
  engine:
    build:
      context: ${PROJECT_ROOT_DIR:-/home/user/milou}/engine
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT:-5432}/${DB_NAME}?sslmode=disable
      - DB_HOST=database
      - DB_PORT=${DB_PORT:-5432}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - JWT_SECRET=${SESSION_SECRET}
      - SSO_CONFIG_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - REDIS_URL=redis://redis:${REDIS_PORT:-6379}
      - DOMAIN=${DOMAIN}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    
  # Nginx built locally
  nginx:
    build:
      context: ${PROJECT_ROOT_DIR:-/home/user/milou}/docker/nginx
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DOMAIN=${DOMAIN}

volumes:
  backend_logs: {}
  engine_logs: {} 